version: '3.1'
services:
  stats-server:
    build: ./stats/server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DATABASE_URL=jdbc:postgresql://stats-db:5432/ewmstat
      - DATABASE_USERNAME=ewmstat
      - DATABASE_PASSWORD=ewmstat
    networks:
      - java-explore-with-me_default

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstat
      - POSTGRES_USER=ewmstat
      - POSTGRES_PASSWORD=ewmstat
    networks:
      - java-explore-with-me_default

  ewm-service:
    build: ./service
    ports:
      - "8080:8080"
    networks:
      - java-explore-with-me_default

  ewm-db:
    image: postgres:14-alpine
    networks:
      - java-explore-with-me_default

networks:
  java-explore-with-me_default: