version: '3.1'
services:
  stats-server:
    build: ./stats/server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DATABASE_URL=jdbc:postgresql://stats-db:5432/ewmstat
      - DATABASE_USERNAME=ewmstat
      - DATABASE_PASSWORD=ewmstat

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstat
      - POSTGRES_USER=ewmstat
      - POSTGRES_PASSWORD=ewmstat

  ewm-service:
    build: ./service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DATABASE_URL=jdbc:postgresql://ewm-db:5432/ewmservice
      - DATABASE_USERNAME=ewmservice
      - DATABASE_PASSWORD=ewmservice
      - STAT_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmservice
      - POSTGRES_USER=ewmservice
      - POSTGRES_PASSWORD=ewmservice