DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS participation_requests CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name  VARCHAR NOT NULL,
    user_email VARCHAR NOT NULL,
    CONSTRAINT uq_email UNIQUE (user_email)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR NOT NULL,
    CONSTRAINT uq_name UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS locations
(
    location_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_lat REAL NOT NULL,
    location_lon REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    event_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_initiator_user_id     BIGINT                      NOT NULL,
    event_category_id           BIGINT                      NOT NULL,
    event_location_id           BIGINT                      NOT NULL,

    event_title                 VARCHAR                     NOT NULL,
    event_annotation            VARCHAR                     NOT NULL,
    event_description           VARCHAR                     NOT NULL,
    event_state                 VARCHAR                     NOT NULL,
    event_date                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_create_date           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_publish_date          TIMESTAMP WITHOUT TIME ZONE,
    event_participant_limit     INTEGER default 0,
    event_is_paid               BOOLEAN DEFAULT false,
    event_is_request_moderation BOOLEAN default false,

    CONSTRAINT fk_event_initiator FOREIGN KEY (event_initiator_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_event_category FOREIGN KEY (event_category_id) REFERENCES categories (category_id),
    CONSTRAINT fk_event_location FOREIGN KEY (event_location_id) REFERENCES locations (location_id)
);

CREATE TABLE IF NOT EXISTS participation_requests
(
    participation_request_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    participation_request_user_id      BIGINT                      NOT NULL,
    participation_request_event_id     BIGINT                      NOT NULL,

    participation_request_status       VARCHAR                     NOT NULL,
    participation_request_created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_participation_request_requester FOREIGN KEY (participation_request_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_participation_request_event FOREIGN KEY (participation_request_event_id) REFERENCES events (event_id),
    CONSTRAINT uc_unique_requester_event UNIQUE (participation_request_user_id, participation_request_event_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_title     VARCHAR NOT NULL,
    compilation_is_pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilation_id BIGINT,
    event_id       BIGINT,

    CONSTRAINT fk_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilations (compilation_id),
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (event_id),

    PRIMARY KEY (compilation_id, event_id)
);